package com.sm.subscribe_google_pubsub.enum

enum class NotificationEnum {

    NONE,
    SUBSCRIPTION_RECOVERED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_PURCHASED,
    SUBSCRIPTION_ON_HOLD,
    SUBSCRIPTION_IN_GRACE_PERIOD,
    SUBSCRIPTION_RESTARTED,
    SUBSCRIPTION_PRICE_CHANGE_CONFIRMED,
    SUBSCRIPTION_DEFERRED,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_PAUSE_SCHEDULE_CHANGED,
    SUBSCRIPTION_REVOKED,
    SUBSCRIPTION_EXPIRED,

}